use_frameworks!

target 'dotLottieR_Example' do
  platform :ios, '9.0'
  pod 'dotLottieR', :path => '../'
  pod 'dotLottieLoader', git: 'https://github.com/eharrison/dotLottieLoader'

  target 'dotLottieR_Tests' do
    inherit! :search_paths

    
  end
end
